---
abstract: 'Create a graph from a Template Toolkit file'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  Carp: 0
  File::Spec: 0
  Graph::Easy: 0
  Template: 2
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-AsGraph
provides:
  Template::AsGraph:
    file: lib/Template/AsGraph.pm
    version: 0.02
  Template::AsGraph::Context:
    file: lib/Template/AsGraph/Context.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/garu/Template-AsGraph
version: 0.02
